<%@ Page Title="" Language="C#" MasterPageFile="~/Administrator.Master" AutoEventWireup="true" CodeBehind="AdminAirline.aspx.cs" Inherits="Final.CreateAirline" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <p>
        &nbsp;</p>
   
       <asp:Panel ID="Panel_ViewAirlines" runat="server">
        <h2>List of Airlines</h2>
           <h2>
               <asp:Label ID="Label_EditTableMessage" runat="server"></asp:Label>
           </h2>
        <br />
        <asp:GridView ID="GridView_Airlines" runat="server" AutoGenerateColumns="False" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
            onrowcancelingedit="GridView_Airlines_RowCancelingEdit" 
            onrowdeleting="GridView_Airlines_RowDeleting" 
            onrowediting="GridView_Airlines_RowEditing" 
            onrowupdating="GridView_Airlines_RowUpdating" >

            <HeaderStyle BackColor="Teal" ForeColor="White" />
            <AlternatingRowStyle BackColor="LemonChiffon" />
            <Columns>
                <asp:BoundField  DataField="id" HeaderText="id" ReadOnly="true"/>
                <asp:BoundField  DataField="name" HeaderText="name"/>
                <asp:BoundField  DataField="logoFilename" HeaderText="logoFilename"/>

            </Columns>



        </asp:GridView>

    </asp:Panel>
  
    <asp:Panel ID="Panel_PromptForDelete" runat="server" Visible="False">
        <asp:Label ID="Label_PromptQuestion" runat="server"></asp:Label>
        <br />
        <asp:Button ID="Button_Delete" runat="server" onclick="Button_Delete_Click" 
            Text="Yes, Delete this airline" />
        <asp:Button ID="Button_Cancel" runat="server" onclick="Button_Cancel_Click" 
            Text="No, Cancel" />
    </asp:Panel>

   
      <asp:Panel ID="Panel_AddAirline" runat="server">
          <h2>Create Airline</h2>

          <table>
          <tr>
          <td>
    <p>
        <asp:Label ID="Label_Message" runat="server"></asp:Label>
    </p>
<p>
        <asp:Label ID="Label1" runat="server" Text="Airline name: "></asp:Label>
        <asp:TextBox ID="TextBox_AirlineName" runat="server"></asp:TextBox>
    </p>
    <p>
        <asp:FileUpload ID="FileUpload_Upload" runat="server" />
    </p>
    <p>
        <asp:Button ID="Button_Upload" runat="server" onclick="Button_Upload_Click" 
            Text="Upload" />
        
    </p>

    </td>
    
    <td>
    <asp:Image ID="Image_Preview" runat="server" Visible="False" />


    </td>



    </tr>
    </table>
<p>
        <asp:Button ID="Button_Submit" runat="server" onclick="Button_Submit_Click" 
            Text="Submit" />
        <br />
    </p>

    </asp:Panel>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>
